name: Teste da Lojinha

on: [push]

jobs:
  rodar-lojinha:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Rodar script
        run: python lojinha.py
