name: Python CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Instalar o Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Rodar o script da lojinha
      run: python lojinha.py
